apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 192.168.99.1 #ipv4 address from vboxnet0 (ifconfig)
    ports:
      - port: 9092  # Port on the Host system